### ISSUE TITLE
Add custom JOSE header arguments

### ISSUE THREAD

**Issue by jacqt** [bryanjos/joken#101]
I need to set custom header arguments to a JWT that I'm creating - what's the best way to do that using Joken - or should I be looking for a different elixir library?

Thanks!

**Comment by bryanjos** [comment]
Hi,

If you want to add a custom claim, you can use `Joken.with_claim/2`. You can add validation for that claim with `Joken.with_validation/2`

```elixir
import Joken

    token = token()
    |> with_claim("my_custom_claim", "custom")
    |> with_validation("my_custom_claim", &(&1 == "custom"))
```

**Comment by cs-victor-nascimento** [comment]
@bryanjos I think we must add this feature to Joken. @jacqt is right as the spec says it should be possible to add header arguments (such as key id) to the JOSE header. I'll have to re-read the spec to be sure, but I think some simple `with_header_arg/2` would cut it.

I will mark this as a feature request so we can track it before 1.0.0 is final.

**Comment by bryanjos** [comment]
ah, the JOSE header. I misunderstood. Yes I agree we should add this

**Comment by jacqt** [comment]
Yeah, I meant the JOSE header - sorry for the confusion!

**Comment by cs-victor-nascimento** [comment]
@bryanjos I've investigated and JOSE accepts it no problem.

We currently ignore the header arguments generated [here](https://github.com/bryanjos/joken/blob/master/lib/joken/signer.ex#L136). We only use to confirm the algorithm passed is the same used in the JWT.

We could add an extra optional parameter to the signer functions. That way extra header parameters will be persisted in the compact representation. 

Unfortunately I can't proceed with the implementation right now. :-1: But as soon as I find more time I could look into it. Feel free to go along if you have time.

**Comment by bryanjos** [comment]
@cs-victor-nascimento no worries. I think I can work on it today

**Comment by cs-victor-nascimento** [comment]
@jacqt #105 has been merged to master. Does it work for you this way? Can we close this one?
