### ISSUE TITLE
Plug documentation - on_verifying function

### ISSUE THREAD

**Issue by Kabal** [bryanjos/joken#106]
I was just updating an old toy project of mine that used Joken plus a Plug that I wrote myself, so I figured I should swap to the Joken.Plug but it took me a while to figure out a few things.

In the documentation and readme it says:

```
plug Joken.Plug, on_verifying: &verify_function/1
```
However the rarity of verify_function is actually 0

Also it might be good to show an example of what verify_function should do e.g:

```
  def verify_function() do
    %Joken.Token{}
    |> with_json_module(Poison)
    |> with_signer(hs256(secret_key()))
  end
```

Also if that is wrong someone let me know but it seemed to work OK :-)

**Comment by cs-victor-nascimento** [comment]
Good catch! We have refactored this part and all tests are using a zero arity function too.

I will update this! THanks for reporting!
