### ISSUE TITLE
Add the ability to enable the 'none' algorithm. Set ability to false by default

### ISSUE THREAD

**Issue by bryanjos** [bryanjos/joken#109]
Add config option to control the ability to use the 'none' algorithm. Set to false by default.

**Comment by potatosalad** [comment]
I recently added similar behavior to [`JOSE.JWS`](https://hexdocs.pm/jose/JOSE.JWS.html) (see also the [Unsecured Signing Vulnerability](https://github.com/potatosalad/erlang-jose#unsecured-signing-vulnerability) section in the readme).  It's currently controlled at the global application level instead of a per-token basis, however.

**Comment by bryanjos** [comment]
Cool! I didn't think about having it at a per token basis. I just assumed it would be global. Now I'm wondering how it would work per token?

**Comment by potatosalad** [comment]
It's definitely the easiest signature format to implement on the signing side of things (if you wanted to bypass the global setting):

```elixir
jwt = %{ "test" => true }
jws = %{ "alg" => "none", "typ" => "JWT" }

signed_none = [
  jws |> JOSE.JWS.to_binary |> elem(1) |> :base64url.encode,
  jwt |> JOSE.JWT.to_binary |> elem(1) |> :base64url.encode,
  ""
] |> Enum.join(".")
```

Verifying is also fairly easy:

```elixir
{verified, jwt, jws} = case JOSE.JWS.expand(signed_none) |> elem(1) do
  %{ "payload" => payload, "protected" => protected, "signature" => "" } ->
    case protected |> :base64url.decode |> JOSE.decode do
      jws = %{ "alg" => "none" } ->
        {true, payload |> :base64url.decode |> JOSE.decode, jws}
      jws ->
        {false, payload, jws}
    end
  _ ->
    {false, nil, nil}
end
```

**Comment by cs-victor-nascimento** [comment]
Actually I believe we are just fine allowing it only as a global state. In fact I appreciate it being turned off by default.

**Comment by potatosalad** [comment]
Also, per token works now on the signing/verifying side with jose if `JOSE.unsecured_signing/0` is enabled:

```elixir
JOSE.unsecured_signing(true)

signed_none = JOSE.JWT.sign(
  %{ "k" => "", "kty" => "oct" }, # jwk
  %{ "alg" => "none" },           # jws
  %{ "test" => true }             # jwt
) |> JOSE.JWS.compact |> elem(1)

true = JOSE.JWT.verify_strict(
  %{ "k" => "", "kty" => "oct" }, # jwk
  ["none"],
  signed_none
) |> elem(0)
```

**Comment by potatosalad** [comment]
Unrelated side note, I'm not sure how I survived this long without realizing that [`Kernel.elem/2`](http://elixir-lang.org/docs/v1.1/elixir/Kernel.html#elem/2) existed for Elixir.  I kept using [`:erlang.element/2`](http://www.erlang.org/doc/man/erlang.html#element-2) throughout my Elixir code which was super clunky.

**Comment by bryanjos** [comment]
#112 should resolve this
