### ISSUE TITLE
JWT exp 

### ISSUE THREAD

**Issue by curtislinden** [bryanjos/joken#114]
I have a JWT signature generated by another library and I expect that the JWT library would return "Signature has expired" when i ask for errors..

Is there any plan to enforce the exp claim?

**Comment by curtislinden** [comment]
I found in the docs how the default token generates this.
            |> with_validation("exp", &(&1 > current_time))

Because I was constructing a token with an existing compat  I needed to be explicit about this validation.

**Comment by sebastialonso** [comment]
Just to clarify, what @curtislinden says doesn't return the expected "Signature has expired" message.

You can have the message by doing `with_validation("exp", &(&1 > current_time()), message: "Signature has  expired")`
