### ISSUE TITLE
ps256 with x5u header

### ISSUE THREAD

**Issue by jschoch** [bryanjos/joken#123]
I have a token that is using ps256 and it has an x5u header with the public key location.  How do I encode the key as a map to feed to the ps256 function?  Any help would be appreciated.

**Comment by cs-victor-nascimento** [comment]
[This](https://github.com/bryanjos/joken/blob/master/test/support/keys_fixture.exs#L41) is an example we use for testing the PS256 algorithm. We use only `x` as parameter. 

Also, the key format is pretty much defined by the [JOSE](https://hex.pm/packages/jose) library. [Here](https://github.com/potatosalad/erlang-jose/blob/master/test/jose_test.exs#L104) is another example. 

Does this help?

**Comment by jschoch** [comment]
i'm not quite sure how to get the right thing from the public key into the map required for verify.  I have somehthing like this

JWT header
```javascript
{
  "x5u": "https://foo.com/public_key",
  "typ": "JWS",
  "alg": "PS256"
}

```

```elixir
keyurl = "https://foo.com/public_key"
%HTTPoison.Response{body: raw_public_key} = HTTPoison.get! keyurl

```

that gets me the pem file.  I have decoded it with:

```elixir
[dkey] = :public_key.pem_decode(raw_public_key)
decoded = :public_key.pem_entry_decode(dkey)
```

how do i get the decoded "certificate" to verify in the correct format?  How did you rsa_key fixtures get mapped in that way from the decoded pem?

**Comment by potatosalad** [comment]
@jschoch Something like the following should work:

```elixir
jws = JOSE.JWS.from("{\"alg\":\"PS256\",\"typ\":\"JWS\",\"x5u\":\"https://foo.com/public_key\"}")
%HTTPoison.Response{body: raw_public_key} = HTTPoison.get!(jws.fields["x5u"])
jwk = JOSE.JWK.from_pem(raw_public_key)
# If the payload of signed_token is a JWT, use the following:
{verified, jwt, _} = JOSE.JWT.verify_strict(jwk, ["PS256"], signed_token)
# If the payload of signed_token just plain text, use the following:
{verified, plain_text, _} = JOSE.JWS.verify_strict(jwk, ["PS256"], signed_token)
```

The value of `verified` should be `true` or `false` and depending on whether you have an embedded JWT or not, `jwt` will be a `%JOSE.JWT{}` struct, or `plain_text` will be a decoded binary.

**Comment by bryanjos** [comment]
Thanks @potatosalad. @jschoch does that help?

**Comment by jschoch** [comment]
I will give it a try

**Comment by bryanjos** [comment]
If that works, I will close this issue
