### ISSUE TITLE
Invalid signature for base 64 encoded secret

### ISSUE THREAD

**Issue by dtrce** [bryanjos/joken#126]
I'm using Auth0 for authentication between phoenix and client side. Auth0 generates a base 64 encoded secret. I can verify the token on jwt.io with the checkbox "secret base64 encoded" checked. I get an invalid signature on jwt.io if I don't check the box. 

I'm seeing the same error when using verify method for a token generated by Auth0. Here's the command I use to verify the token: 

```
verify_token = "ey....." |> token |> with_signer(hs256(auth0_secret)) |> verify
```

I tried doing `auth0_secret = Base.decode64("client secret..")` but I'm getting an erorr. One thing I noticed that the auth0 secret has "-" character, which fails while decoding with an error: non-alphabet digit found: "-" (byte 45)

**Comment by dtrce** [comment]
I figured out the workaround, I had to use Base.url_decode64 instead of Base.decode64. This works: 

`{:ok, auth0_secret} = Base.url_decode64("client secret")`

It would be good if Joken had a flag that decodes the token if it is base 64 encoded.

**Comment by cs-victor-nascimento** [comment]
Hi @dtrce!

I did not quite understand your whole scenario. Can you paste a working code that reproduces the issue? I can use jwt.io to generate a token and verify it with Joken. Actually, we used it quite often during development. 

If you could paste a working code that reproduces the issue I'll take a look at it. 

Thanks!

**Comment by bryanjos** [comment]
I guess the best option is to add an option to not base64 encode the secret?

**Comment by dtrce** [comment]
Client secret is generated by a third party provider like auth0 or Firebase, so there isn't much control on how they encode it.

I guess Joken doesn't really need any options since there are many ways a secret could be encoded unless there is a way to detect it automatically.

**Comment by bryanjos** [comment]
It sounds like this may have been resolved, but an action item here might be to add the option to skip base64 encoding if item is already encoded.

**Comment by bryanjos** [comment]
I'm going to close this. After looking into this some more, there could be some breaking changes to adding an option for this and I'm not sure if the need for something like this is high enough. Also there are a couple of existing work arounds. One is discussed here and the other would be to pass into the Signer a full jwk map.
