### ISSUE TITLE
How to use verify?

### ISSUE THREAD

**Issue by hopewise** [bryanjos/joken#127]
I am sorry that I am writing this here, as this is not an issue, however I am new to elixir and I need to know how to use verify:

```
my_verified_token = "my_verified_token "
    |> token
    |> with_signer(hs256("myKey"))
    |> verify
```

but how to do if statement based on if the token is verified or not?

like:

```
if verified do
#
else
#
end
```

Also, how would I get the values of the payload within the token?

thank you

**Comment by bryanjos** [comment]
Hi, there are a couple of ways to do this. 

First, using your example:

```elixir
my_verified_token = "my_verified_token "
    |> token
    |> with_signer(hs256("myKey"))
    |> verify
```

You can use [get_error](https://hexdocs.pm/joken/Joken.html#get_error/1) to get the error message if it exists:

```elixir
error = get_error(my_verified_token) # Will either be the string error message or nil
if error do
#
else
#
end
```

Or for something more idiomatic, you can use [get_data](https://hexdocs.pm/joken/Joken.html#get_data/1) with a case statement:
```elixir
case get_data(my_verified_token) do
  {:ok, payload} ->
    # payload is a map of the claims on the token
  {:error, msg } ->
    # msg is the validation error message
end
```

**Comment by hopewise** [comment]
Thanks for clarification:)
