### ISSUE TITLE
Allow optional messages for failed validations for better debugging/scenario handling

### ISSUE THREAD

**Issue by IamfromSpace** [bryanjos/joken#128]
If a token has multiple validations, it is difficult to know which validation has failed and how to respond.  Custom messages could be included with each validation that could be pattern matched against so the proper action can be performed.

In this example:
```
my_verified_token = compact_token
  |> token
  |> with_validation("exp", &(&1 > :os.system_time(:seconds)))
  |> with_validation("admin", &(&1 == true))
  |> with_signer(hs256("temp_secret"))
  |> verify!
```
If the token does not pass its validation, I get an "Invalid payload" error, but this doesn't tell me whether I should have them login again (401 and with a redirect to login), or tell them they don't have the privileges to access the resource (403).

If I want to respond to each individual case, I am restricted to a single validation, then to handle the claims in the controller.

My proposal is as follows: add an optional third parameter to `with_validation` which describes the error, should validation fail.  The first failed validation populates the returned `error` key, and all validation errors are added to an `errors` list.

No breaking change, but added control.

I'm working on the code now and will open a PR soon; I can change the approach if there are any concerns.

**Comment by cs-victor-nascimento** [comment]
Nice one! We just have to be careful when using this to give authentication systems too much information. Most of the time we don't want an authenticated endpoint to reply with: "your token has a role we don't recognize", "your token id was not found" and etc. 

Your use case is a valid one and I am :+1: on this feature and I think we must support this. I would only be very careful with the docs to avoid leading users on leaving too much info on responses to clients.

**Comment by IamfromSpace** [comment]
Awesome, I'll get the PR in asap!

And agreed on the information-leak docs.  I'll try to write up some docs that make it clear the risks if improperly handled.

**Comment by cs-victor-nascimento** [comment]
@bryanjos what do you think?

**Comment by bryanjos** [comment]
Sounds like a good idea!

**Comment by IamfromSpace** [comment]
Sweet.  Got the WIP here: [9eefe71f4a8e7090fba793dec6a8a6b218b66fe4](https://github.com/IamfromSpace/joken/commit/9eefe71f4a8e7090fba793dec6a8a6b218b66fe4).

Think that all works currently and all previous tests pass.  Need to add new tests and docs and then I'll open the request.

Cheers!

**Comment by bryanjos** [comment]
Merged in the PR so I'm closing this
