### ISSUE TITLE
[Critical] Validations are Skipped if tokens do not contain the validated property

### ISSUE THREAD

**Issue by IamfromSpace** [bryanjos/joken#129]
When writing tests for #128, I discovered that validations were ignored if the token payload did not include the field/prop that was being validated.  This could accidentally open critical security holes.

For example, if I have a route that issues a token for a regular user:
```
my_issued_token = %{userId: id}
  |> token
  |> with_signer(hs256("my_secret"))
  |> sign
  |> get_compact
```
And a route that needs admin privileges to access:
```
my_verified_token = compact_token
  |> token
  |> with_validation("admin", &(&1 == true))
  |> with_signer(hs256("my_secret"))
  |> verify!
```
That above token accidentally has admin access.  To prevent it, I have to explicitly set the admin property.
```
my_issued_token = %{userId: id, admin: false}
  |> token
  |> with_signer(hs256("my_secret"))
  |> sign
  |> get_compact
```
This is problematic for a couple reasons:
* For security, least privilege should be assumed
* If tokens are extended they need to be updated everywhere or risk accidental access.

I have a pull request ready to go that patches v1.0.0, v1.1.0, and v1.2.0, so they can all be published right away.

edit and aside:  I wanted to have the code ready to go right as this was reported so it could be patched asap.  In the future, a private channel for discussing security flaws could included in the README.md so an approach for fixing can be discussed with project maintainers without widely broadcasting a potential hole.

**Comment by bryanjos** [comment]
Thanks for finding this and for the PR. I can get to work on publishing the updates now

**Comment by bryanjos** [comment]
Published:
https://hex.pm/packages/joken/1.0.1
https://hex.pm/packages/joken/1.1.1
https://hex.pm/packages/joken/1.2.1

I'll have to think about how to handle private discussions of these kinds of issues, but its a good idea.

**Comment by redvers** [comment]
At some point there was a way to enable the ability to open private issues for security concerns.

Secondly, massive kudos for backporting to all major revisions - many people would not have.

**Comment by IamfromSpace** [comment]
@bryanjos glad to help out!  @redvers thanks! I'm one of those guys always on the soap box about it, so I'd better practice what I preach, haha.
