### ISSUE TITLE
1.3.x alignment?

### ISSUE THREAD

**Issue by nicolafiorillo** [bryanjos/joken#132]
Hi Bryan,
trying to compile it with Elixir 1.3.1, some warnings occurred (also from old version dependencies).
Are you going to align _joken_ project to 1.3.X?

Thanks!

**Comment by bryanjos** [comment]
Hi Nicola,
I can take a look this weekend and update anything that is breaking and/or fix warnings

**Comment by bryanjos** [comment]
Merged in PR to resolve these warnings. Will be in the next version

**Comment by freiden** [comment]
Hi @bryanjos,
Is it possible to know the next release date of this new version please?

**Comment by aphillipo** [comment]
Hi @freiden - you can reference github in mix for the time being... 

{:joken, git: "https://github.com/bryanjos/joken.git", ref: "15d3c18a1f3bfbe6fbed9d22192a36fe3114b2d1"}

**Comment by bryanjos** [comment]
I'll probably publish either tonight or tomorrow when I get a chance to update the changelog.

**Comment by bryanjos** [comment]
Published as 1.2.2

**Comment by freiden** [comment]
Ok thanks.
