### ISSUE TITLE
Allow configuration of json library

### ISSUE THREAD

**Issue by jeregrine** [bryanjos/joken#14]
I am a pretty big fan of the elixir json package poison and it gets similar performance to jsx. 

Would it be possible to make the json library configurable?

**Comment by jeregrine** [comment]
Also would like 1 less dependency :)

**Comment by bryanjos** [comment]
I would have to look into it and figure out how but it should be possible.

**Comment by jeregrine** [comment]
Looks like they have the same API except that poison returns and accepts maps natively.

**Comment by bryanjos** [comment]
Yeah I know Phoenix did/does something similar. It's possible and it's a good idea. Just trying to figure out the best way to handle it. I've been using poison for most things these days as well.

**Comment by jeregrine** [comment]
I’d be :+1: on just switching to it :)

**Comment by bryanjos** [comment]
So I created a branch using Poison. I think today I'm going to create another branch that creates a behaviour and have users implement that and pass in the implementation. I'm wondering if it would be best to turn it into a server and have users of it pass in the configuration that way and/or look at the config and check for settings there as well.

**Comment by bryanjos** [comment]
Referencing the pull request here in case anyone is interested. If there aren't any objections or feedback I may merge it in today or tomorrow and it will be the version 0.10.0 of Joken.

https://github.com/bryanjos/joken/pull/16

**Comment by bryanjos** [comment]
Updated the Hex version to 0.10.0. You are now able to use any json library you want via implementing the Joken.Codec behaviour and passing it in.
