### ISSUE TITLE
Unclear if it's possible to decode a token in string form from the docs

### ISSUE THREAD

**Issue by joakimk** [bryanjos/joken#142]
Is it possible to do that using this library? Seems it was in an earlier version.

If there is, maybe you could write it a bit like the [ruby-jwt](https://github.com/jwt/ruby-jwt) docs. Encode and then decode scenarios.

**Comment by bryanjos** [comment]
Yes it is possible

```elixir
import Joken

my_string_token = "some_token"

my_verified_token_struct = token(my_string_token)
|> with_signer(hs256("my_secret"))
|> verify
```

From there you can get the claims from `my_verified_token_struct` either directly or through the helper functions
