### ISSUE TITLE
Unlock poison dep

### ISSUE THREAD

**Issue by QuentinFchx** [bryanjos/joken#150]
Poison lib is now 3.x (https://github.com/devinus/poison).
Is it possible to unlock the dep ?
currently `{:poison, "~> 1.5 or ~> 2.0", optional: true}`

**Comment by leifg** [comment]
What's the status on this? I just tried it out with poison 3.0, the tests work.

**Comment by cs-victor-nascimento** [comment]
Opened simple PR that unlocks it. All tests passed :)

**Comment by leifg** [comment]
👍

**Comment by bryanjos** [comment]
Published: https://hex.pm/packages/joken/1.3.2
