### ISSUE TITLE
Add cross claims validations 

### ISSUE THREAD

**Issue by marpo60** [bryanjos/joken#154]
Hi,

Im facing the following situation: in order to validate a claim I need to know the value of other claim.

Right now this is not possible given that [with_validation/4](https://hexdocs.pm/joken/Joken.html#with_validation/4) function only takes into consideration the the claim value and [as far as I see](https://github.com/bryanjos/joken/blob/e004dc0f33069813e92823c095f00f7742c3de1b/lib/joken/signer.ex#L222) there is no one way access other claims inside the validation function.

One solution would be to have the possibility of doing something like this:
```
token
|> with_validation(["field_1", "field_2"], &(&1 == &2))
```

What do you think?

**Comment by cs-victor-nascimento** [comment]
You are right that there is no clean way of implementing it right now. We could add a `with_token_validation/3` for these cases. The rules would be that it must be called __after__ all claim validations.

@bryanjos WDYT?

**Comment by bryanjos** [comment]
We could add something like that. Maybe looks like this?

```elixir
validated_token = token
  |> with_token_validation(fn claims -> claims.my_claim == claims.my_other_claim end, "Invalid Claims")
```

Why would it have to be after the other claim validations? Should we pass in the entire token or just the claims?

**Comment by cs-victor-nascimento** [comment]
I`d pass only the claims as to avoid messing with the JOSE header or the signature. 

I thought about prioritizing `with_validation/4` calls up front because if you want to cross-validate claims it is better if they are already valid. I mean: you can have validations for specific claims and then a cross validation scenario. What do you think?

**Comment by bryanjos** [comment]
The more I think about it, the more I like @marpo60's suggestion. It is explicit in the claims you want passed in to validate. It would be something we could implement easily I think (add a check for a list of claim names, use `apply` to send them to the function that should have an arity matching the length of the list). We wouldn't have to add a special case for the token validation.

I don't think order should matter much if we are just going to run them all anyway.

@cs-victor-nascimento what do you think?

**Comment by marpo60** [comment]
I don't think order should matter either.
Both option `with_token_validation` and `with_validation` with a list of claims would work.

Once we know the way we want to proceed I can start working on a PR

**Comment by cs-victor-nascimento** [comment]
Yeah you are right! I was micro optimizing... I`ve forgotten that we run all validations.

It makes sense :)

**Comment by bryanjos** [comment]
My vote is for going with updating `with_validation/4` to optionally accept a list of claims. I think the only changes needed would be in the validation code in the Signer module.
