### ISSUE TITLE
Unable to decode JWT without signature

### ISSUE THREAD

**Issue by loeschg** [bryanjos/joken#157]
I have the following JWT which is decoded fine with other online tools:

```
eyJhbGciOiAiSFMyNTYiLCAidHlwIjogIkpXVCJ9.eyJleHAiOiAxNDgxMjU4Mzk2LCAiaXNzIjogIjhmZGM3OTY2LWI5YTctNDc1Ni1hMzQ0LTVhODRlNWFhNDRhYSIsICJwcm4iOiAiMjQ0ODcyMiIsICJqdGkiOiAiSFNXbDJURWlsdUpld0pxcEpUNGIiLCAiY29udGV4dCI6IHsicm9vbV9pZCI6IDMzNjc5MjcsICJ1c2VyX3R6IjogIkFtZXJpY2EvQ2hpY2FnbyJ9LCAiaWF0IjogMTQ4MTI1NzQ5NiwgInN1YiI6ICIyNDQ4NzIyIn0.yqCQSdrKn8RxEM81cYBKZoc6qXKYIOHrvY81rxGLWmc
```

I need to first decode the jwt (without the proper signature) to grab a token to get the proper secret to verify the JWT. I can't seem to get this to work with this library. Is this use case supported?

**Comment by loeschg** [comment]
Ugh. Looks like I missed `Joken.peek/1`.

**Comment by bryanjos** [comment]
It's in the docs already and I think that's sufficient. If it becomes a bigger use case than it is currently, I then we can revisit putting info there.

**Comment by loeschg** [comment]
👍
