### ISSUE TITLE
{:error, "Invalid signature"}. Expected {:ok, socket} or :error

### ISSUE THREAD

**Issue by hopewise** [bryanjos/joken#158]
hello,

I am sure that I am using a valid token and the same algorithm used with the issued JWT token that I am trying to verify, however, I still get error {:error, "Invalid signature"}

```
my_verified_token = sent_token
    |> token
    |> with_signer(hs256(Application.get_env(:trackware, :jwt_secret_key)))
    |> verify

    case get_data(my_verified_token) do

      {:ok, payload} ->
           # this was never reached
      {:error, msg } ->
           # this is always reached!
        {:error, msg}
    end
  end
```
I am using the latest version of joken, here is my deps:

```
defp deps do
    [{:phoenix, "~> 1.2.0"},
     {:phoenix_pubsub, "~> 1.0"},
     {:phoenix_ecto, "~> 3.0-rc"},
     {:postgrex, ">= 0.0.0"},
     {:phoenix_html, "~> 2.6"},
     {:phoenix_live_reload, "~> 1.0", only: :dev},
     {:gettext, "~> 0.9"},
     {:cowboy, "~> 1.0"},
     {:ex_aws, ">= 1.0.0"},
     {:poison, "~> 1.2"},
     {:httpoison, "~> 0.9.0"},
     {:joken, ">= 1.3.2"},
     {:edeliver, "~> 1.4.0"},
     {:exrm, "~> 1.0.3"},
     {:cqex, "~> 0.2.0"},
     {:cqerl, github: "matehat/cqerl"},
     {:uuid, "~> 1.1", override: true},
     {:remote_monitor, "~> 0.1.0", only: :dev}]
  end
```

elixir version:
```
✗ iex
Erlang/OTP 19 [erts-8.0.2] [source] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Interactive Elixir (1.3.2) - press Ctrl+C to exit (type h() ENTER for help)
```

Any idea?

**Comment by cs-victor-nascimento** [comment]
Usually for me this boils down to whitespace or new line characters somewhere. Try to log the call to `Application.get_env(:trackware, :jwt_secret_key)` and see if there is a new line involved. 

Otherwise it should pass. It should have no trouble at all with HMACs. 

Another thing that comes to mind is that the token might have some of its characters escaped. It can happen if you are receiving the token through query parameters (which I would not advise...).

**Comment by hopewise** [comment]
Thanks, but I found that if I remove the "Bearer " from the token, it will work normally!

**Comment by cs-victor-nascimento** [comment]
All right! I will be closing this issue then. If anything appears after that, please reopen it.
