### ISSUE TITLE
Help figuring out how to resolve "kid" field in JOSE header

### ISSUE THREAD

**Issue by smitchelus** [bryanjos/joken#159]
Hi, I'm gotten basic decoding/verification going using Joken without issue. However, I will be receiving tokens with a JOSE header that provides a "kid" attribute to allow us to identify which key was used to sign the token. I have yet been able to figure out how I can go about reading inserting a key lookup function into the pipeline with Joken. I did see the peek function. However, that appears to only return the claims from within the token, and nothing from the JOSE header. Can you please point me in the right direction?

In case it helps, here's an example of my claims and JOSE headers in clear text (made up/limited values):

```
claims: {"iss"=>"my.service", "sub"=>"test@test.com"}
JOSE header: {"typ"=>"JWT", "alg"=>"RS512", "kid"=>"my.service.key"}
```

**Comment by bryanjos** [comment]
@smitchelus hi, I think you are correct there isn't anything there for header verification. You would need to see what is in the header in order to validate it, is that correct?

**Comment by smitchelus** [comment]
Correct, at a minimum, I need to get access to the header JSON so that I could pull the kid value to lookup the correct key to then verify the token.

**Comment by bryanjos** [comment]
Got it. Joken uses the peek function from erlang-jose to handle this. Looks like there is a peek_protected as well to get the header info.

I'll make an issue to add in a way to peek at the header and hopefully get it resolved tonight or tomorrow. Would that work?

**Comment by smitchelus** [comment]
That would be perfect. Thanks!

**Comment by bryanjos** [comment]
Added `Joken.peek_header/1` in version 1.4.1 https://hex.pm/packages/joken/1.4.1

**Comment by smitchelus** [comment]
Looks great. Thanks so much!
