### ISSUE TITLE
Why not pass conn to the plug callback functions? 

### ISSUE THREAD

**Issue by raarts** [bryanjos/joken#170]
When the Plug is used in Phoenix, one would also like to put the claims into the conn structure, which the Plug does not pass. So currently it's required to decode the token twice, which incurs extra cpu time.

Would it be an idea to pass the conn to the callbacks?

**Comment by aphillipo** [comment]
Looking at the code it seems the plug should be setting :joken_claims ?

https://github.com/bryanjos/joken/blob/4e7d34f4020ee1346f4c437e0c555589e1173132/lib/joken/plug.ex#L181

I suppose if it's not doing this that is a bug?

**Comment by raarts** [comment]
Whoops! Completely missed that. Thanks!
