### ISSUE TITLE
Regarding validation for "exp"

### ISSUE THREAD

**Issue by the-shank** [bryanjos/joken#171]
I am generating a token with an expiry of 1 seconds and a single other claim (`email`) as below:

```elixir
jwt = 
  token()
  |> with_claims(%{email: "testemail"})
  |> with_exp(1)
  |> with_signer(hs256("secret"))
  |> sign
  |> get_compact
```

Then I sleep the process for 2 seconds

```elixir
:timer.sleep(:timer.seconds(2))
```

Next I verify the token, including the validation for `"exp"`

```elixir
verified_token =
  jwt
  |> token
  |> with_validation("exp", &(&1 > current_time))
  |> with_signer(hs256("secret"))
  |> verify
```

From what I understand, this token should fail at the validation due to `"exp"`, but it is not. Is my understanding incorrect or am I missing something?

**Comment by cs-victor-nascimento** [comment]
What is happening is this:

`token()` function adds a *dynamic* claim "exp" to the struct. This means it adds "exp" claim with:

```elixir
%Token{}
    |> with_claim_generator("exp", fn -> current_time() + (2 * 60 * 60) end)
```

What this means is that the validation depends upon a dynamic value (in that case the `current_time()`) which is evaluated only when you call sign. To do that we have a field in the struct to keep that function `fn -> current_time() + (2 * 60 * 60) end` for being evaluated only when you call sign. 

So, even though you have added a fixed value for the field, you still have the function being evaluated lazily when you call `sign()` and that overrides your fixed value. In practice, if you decode your compact token you will see that it has a value for the "exp" claim different than that of 1. It should be 2 hours in seconds.

If you truly intend to use the default values plus an override of a dynamic value, you could always do it like this:

```elixir
    jwt = 
      token()
      |> with_claims(%{email: "testemail"})
      |> with_claim_generator("exp", fn -> 1 end)
      |> with_signer(hs256("secret"))
      |> sign
      |> get_compact
```

We are aware that this is a bit *surprising*. We might change this API a little to have it less surprising in the future...

Why a dynamic value you might ask. Well, when you use a Plug or something like that, you want to have the configuration of your token kept someplace (like in a config field) but its values being dynamically generated when you sign the token. That was the reasoning. 

Hope this helps \o/ If not, please feel free to re-open the issue.

**Comment by the-shank** [comment]
Thank you for the detailed explanation ! Makes sense now :)

Do you think it would be a good idea to add this information to the README file?

**Comment by cs-victor-nascimento** [comment]
Surely! That would help a lot! Can you send us a PR with that?

Thanks!

**Comment by the-shank** [comment]
Great, will do it today itself!

**Comment by anthonylebrun** [comment]
"a bit surprising" <- this :D

**Comment by victorolinasc** [comment]
Yeah I know... I have some plans on updating this library during January to a less confusing API, better docs and more examples. Stay tuned :)
