### ISSUE TITLE
Clean optional native deps

### ISSUE THREAD

**Issue by cs-victor-nascimento** [bryanjos/joken#178]
I would like to remove all the optional extras besides libsodium from the repo. We don't have clear compiling instructions and after digging a little bit further, they are not being updated and haven't lost their WIP status. So, my guess is it's safer to just remove them. We could even remove libsodium but I think it has a more stable status currently. Some of the others are tracking old versions of upstream repos. They fail to compile with more modern tooling and that only makes contribution harder.

**Comment by victorolinasc** [comment]
Fixed on #185
