### ISSUE TITLE
High reduction usage

### ISSUE THREAD

**Issue by sb8244** [bryanjos/joken#186]
Hi, I'm tracing an issue with jose_server having a very large number of reductions in production. I'm not entirely sure of throughput level, but let's say it's 100-1000 calls per minute.

I believe that I've traced the `jose_server` process back to the `json_module` gen_server call with `Poison` as the argument. I traced this into Joken to line https://github.com/bryanjos/joken/blob/e5194c5f5a2b0cca1fe2014bcf99fcd1dbfd8b9a/lib/joken.ex#L65.

Is there a need to call `JOSE.json_module(Poison)` every time that I cast a binary to a token? If I called this once on application boot, would that satisfy the need?

**Comment by victorolinasc** [comment]
We are changing this in Joken 2.0 (which will be a non-backwards compatible update). 

You are right that you can do it only at application bootstrap. Internally this is implemented in JOSE as gen_server that holds its config. See source [here](https://github.com/potatosalad/erlang-jose/blob/master/src/jose_server.erl#L109). After set once, it is kept on an ets table.

**Comment by sb8244** [comment]
Thanks @victorolinasc . For now, I solved this by manually casting to `Joken.Token` struct and setting the json_module field to `Poison`

**Comment by weixiyen** [comment]
Thanks, will manual cast for now on Joken 1.3 (I have ex_twilio which deps on 1.x still).

Will edit to confirm that manual casting fixes the issue, but I'm guessing that was it.

**Comment by victorolinasc** [comment]
That was one of the reasons we went with 2.0. 

Sorry for any inconveniences! I'll take a look at this dep to see if I can propose a PR for updating it to 2.0 once it its out.

**Comment by weixiyen** [comment]
No worries.  Thanks!

**Comment by weixiyen** [comment]
Just writing back to confirm that this is indeed the bottleneck, and manual casting solved everything, thanks for the awesome library.
