### ISSUE TITLE
rebar.config lists a dependency to a branch instead of a fixed version.

### ISSUE THREAD

**Issue by joudinet** [bryanjos/joken#202]
Hi,
I'm in the process of adding your project to Buildroot (see buildroot.org) but I notice it depends on a project without specifying which version:
```
{deps, [
	{base64url, ".*", {git, "git://github.com/dvv/base64url.git", {branch, "master"}}}
]}.
```
I suggest you fix the version at least when you make a release of your project. Thanks.
Best,

**Comment by victorolinasc** [comment]
No problem. This is a dependency of [erlang-jose](https://github.com/potatosalad/erlang-jose/).
