### ISSUE TITLE
Base 64 encoded key?

### ISSUE THREAD

**Issue by alanpeabody** [bryanjos/joken#21]
This may very well be user error, but I have been trying to use Joken with a JWT generated by a third party (auth0.com) and I am running into some problems verifying the signature.

Running the same token/signature provided through http://jwt.io works, but only if I click the "secret base64 encoded" check box.

Does Joken support encoded secret keys like this?

If it does not yet I am happy to help if given a little guidance (I am pretty unfamiliar with JWT, this is the first time I have used it).

I am using the master branch, not the hex.pm release.

Thanks!

**Comment by bryanjos** [comment]
Currently it does not base64 encode the secret. Probably the best way to handle it is to make it a config item and base64 encode the secret_key depending on the value. Then pass that to the Joken.Token.encode function.

For instance, with Joken.encode, the change can be

```elixir
  def encode(payload, claims \\ %{}) do
    secret_key =  Application.get_env(:joken, :secret_key)
    json_module = Application.get_env(:joken, :json_module)
    algorithm =   Application.get_env(:joken, :algorithm, :HS256)
    encode_secret_key? = Application.get_env(:encode_secret_key?, false)
    
    if  encode_secret_key? do
        secret_key = Base.encode64(secret_key)
    end

    Token.encode(secret_key, json_module, payload, algorithm, claims)
  end
```

And then for Joken.decode you would have to make sure to do the same check before passing it in as well.

**Comment by alanpeabody** [comment]
Great, thanks Bryan. I will take a stab at this tonight.

**Comment by alanpeabody** [comment]
Fix in: https://github.com/bryanjos/joken/pull/22

**Comment by dtrce** [comment]
Hello,

What was the actual fix for this? I'm running into the same issue with auth0 secret. I am using this 

```verify_token = "ey....." |> token |> with_signer(hs256(Base.encode64(auth0_secret))) |> verify```

but getting an invalid signature error.

**Comment by bryanjos** [comment]
@dtrce the code changed completely since this issue, but the resolution was to set a configuration to not base64 encode the given secret. It looks like that configuration was lost in the rewrite, but if it's something that's needed, we can add the option to not encode the secret that is passed in.

Alternatively, in your example, you could try
```elixir
verify_token = "ey....." |> token |> with_signer(hs256(auth0_secret)) |> verify
```

And see if that gives you the expected result

**Comment by dtrce** [comment]
I tried without Base.encode64 but receving an error "Invalid Signature"

**Comment by bryanjos** [comment]
I will take a look when I get some free time

**Comment by bryanjos** [comment]
actually @dtrce do you mind creating a new issue for this and some info on how to reproduce it?
