### ISSUE TITLE
Define behaviour to handle the addition and/or checking of claims

### ISSUE THREAD

**Issue by bryanjos** [bryanjos/joken#26]
For instance if someone wants to add claims to a token, or define a custom jti algorithm to be used when encoding a token, etc. 

```elixir
#Should return a new payload with whatever claims added to it
add_claims(payload)

#Encodes the payload. Same as  (and would replace) Joken.Codec.encode
encode(payload)

#Decodes the token. Same as  (and would replace) Joken.Codec.decode
decode(token)

#After the signature has been validated and payload decoded, 
#this would take the payload and validate the claims
validate_claims(payload)
```

This should allow for more customization. We can add default implementations for some of the claims (i.e. the time based ones), but still allow for a custom algorithm to be used instead.

**Comment by jeregrine** [comment]
@bryanjos add_claims will need to accept some claims :) 

I don't super have a need for this but I keep my usage of JWT to pretty basic. Looks good to me.

**Comment by bryanjos** [comment]
The idea would be that the implementor of the behaviour would add the claims to the payload within add_claims.

**Comment by bryanjos** [comment]
I've been thinking about this some more and the idea I currently have is to define something like below

```elixir
defmodule Joken.Claims do
  use Behaviour

  defmacro __using__(_opts) do
    quote do
      @behaviour Joken.Claims

      def exp(payload) do
        123456789
      end

      def validate_exp(payload) do
        {:ok, payload}
      end
       .
       .
       .
      defoverridable [encode: 1, decode: 1, exp: 1, validate_exp: 1, ...]
    end
  end

  @doc """
  encode can take either a map or a keyword list or both and return a string.   
  """
  defcallback encode(Joken.payload) :: String.t
  
  @doc """
  decode can take a string and return a map or a keyword list. 
  """
  defcallback decode(String.t) :: Joken.payload
end
```

Where every claim function also had an associated validate_claim function. One for providing the claim and one for validating the claim. The default functionality would work how it does now, but passing some the uses the above (probably by adding it to the configuration) would use the functions that have been overridden for filling in the associated claims and validating them. The only thing I haven't thought about yet was how to pass on adding a claim. Maybe just `nil`? It would be the default to not add the claim.

**Comment by bryanjos** [comment]
Not finished yet but #33 is the PR I'm working on for this.
