### ISSUE TITLE
Signature verification is not enforced

### ISSUE THREAD

**Issue by cs-victor-nascimento** [bryanjos/joken#27]
Hello! Nice utility library :+1: 

I just think that I've found a somewhat strange behaviour. [Here](https://github.com/bryanjos/joken/blob/master/lib/joken/token.ex#L64), the first thing you do is to split the JWT and if it has only 2 parts you keep on going regardless of the algorithm passed. So, even if I configure it to ONLY use HS256, if I receive a token that has no signature, it will go on as a valid token.

Here's a snippet: 
![screenshot from 2015-05-13 16 12 58](https://cloud.githubusercontent.com/assets/7049728/7618787/f4eac1c6-f98a-11e4-82b8-a54196575106.png)

The second time I decode it, I remove the signature and it decodes properly all the same. If I encode some valid JSON (like changing the sub claim) and simply remove the signature it will pass all the same. Even if the JOSE header has the alg correctly as HS256. 

I guess there should be someway to ensure signature verification if the algorithm is passed. Something like:

```elixir
defp verify_signature(token, key, algorithm) do
    case String.split(token, ".") do
      [ _header64, _payload64 ] ->
          if algorithm == :none || is_nil(algorithm) do
              { :ok, token }
          else
              { :error, "Missing signature" }
      [ header64, payload64, jwt_signature ] ->
        signature = :crypto.hmac(Utils.supported_algorithms[algorithm], key, "#{header64}.#{payload64}")

        if Utils.base64url_encode(signature) == jwt_signature do
            { :ok, token }
        else
            {:error, "Invalid signature"}
        end
      _ ->
        {:error, "Invalid JSON Web Token"}        
    end

  end
```

If that is ok I can send a PR!

**Comment by bryanjos** [comment]
:+1:  that looks perfect! I just took a look at the spec and what you proposed is the correct solution. If you make a PR I will accept it and try to make a release for hex tonight as well.

**Comment by bryanjos** [comment]
I went ahead and fixed the issue in the PR below
https://github.com/bryanjos/joken/pull/28

If everything is ok I'll merge it in and update joken in hex

**Comment by cs-victor-nascimento** [comment]
Please do! Sorry it took me a while. I was attending other things.

Way to go!

**Comment by bryanjos** [comment]
No worries. Thanks for pointing this out!
