### ISSUE TITLE
Validate claim

### ISSUE THREAD

**Issue by hassox** [bryanjos/joken#38]
The new config setup is great, but one thing I found left me wanting a little more ;)

When validating claims, there's no way to validate many of them because all you have is the claims themselves and the key to validate. For example if I want to validate the :aud I might have something like:

    Joken.decode(string, aud: "MySystem")

Unfortunately as it stands today, I can't check this since the [{aud: "MySystem"}] is not passed through to the validate_claim function.

Another example. Imagine an background worker which needs to call background (s2s) services. The exp should be checked against the time the request was made rather than what the time is now since it may have been sitting in the queue for a while.

I think it should be as simple as passing through the options to the verify_claims functions as a 3rd argument. However this breaks the current contract. 

I'd be happy to put a PR together if you think this would be decent.

**Comment by bryanjos** [comment]
I think I understand. The defcallback validate_claim/2 is given the atom representing the claim and the entire payload. I think that's what you want correct? Right now with that callback you would have to get the claim out of the payload yourself to validate it. I figured there might be instance where you need other info within the payload the validate a claim.

I see I also named the helper function validate_claim/4. I didn't realize they had the same name until now :). I'll probably move those helper functions into a Helpers module.

**Comment by bryanjos** [comment]
Maybe it makes more sense to have something like

```elixir
defcallback validate_claim({Joken.claim, any}, Joken.payload) :: :ok | {:error, String.t}
```

Where the first value is the a tuple containing the claim's name and value, and the second is the entire payload? I don't know if that resolves this issue though. 

I'm open to any changes that should be made. I'm just trying to understand the issue.

**Comment by hassox** [comment]
I think what's currently there is the atom for the claim, and the payload. What's missing is the ability to pass in a map/keyword list that contains assertions that should be validated against.

Assume that the payload contains:

    payload = %{ aud: "something" , iat: .... }

When I decode the token:

    Joken.decode(jwt, aud: "something else")

I'd expect to be able to compare the :aud found in the jwt with the one passed in.

    def validate_claim(:aud, payload, options) do
      claim_aud = Dict.get(payload, :aud)
      expected_aud = Dict.get(options, :aud)
    
      if expected_aud && expected_aud != claim_aud do
       { :error, :invalid_aud }
      else
        :ok
      end
    end

**Comment by bryanjos** [comment]
Ah I see what you mean. Yes, if you put together a PR I will accept it.

**Comment by bryanjos** [comment]
@hassox I started working on this. Check it out #41. I'll probably finish it tomorrow if all is good

**Comment by bryanjos** [comment]
Also @hassox would you like to be a collaborator?

**Comment by bryanjos** [comment]
Updated with options passed in and keys from options are also passed to validate_claim
