### ISSUE TITLE
jose_hs_benchmark uses invalid Joken.CurrentTime.current_time()

### ISSUE THREAD

**Issue by ktekinay** [bryanjos/joken#399]
The file jose_js_benchmark.exs references `Joken.CurrentTime.current_time()`, but this results in an error.

One fix is to change those to:

```
Joken.CurrentTime.OS.current_time()
```

**Comment by victorolinasc** [comment]
Thanks a lot! Will fix this too! New version incoming soon.

**Comment by victorolinasc** [comment]
Fixed on main! Thanks once again
