### ISSUE TITLE
Update for the README Joken.Config example implementation to not use atoms

### ISSUE THREAD

**Issue by werbitzky** [bryanjos/joken#42]
I was using the hassox/guardian authentication framework, when I discovered a problem with their Joken.Config implementation (Guardian.JWT) which used the Poison library in a not recommended way:

https://github.com/hassox/guardian/issues/13

in the joken README there is a Joken.Config example implementation where atoms are also used as keys:

```elixir
    def decode(binary) do
      Poison.decode!(binary, keys: :atoms!)
    end
```

which can lead to a lot of pain:

https://github.com/devinus/poison#parser

I suggest to change the documentation to prevent wrong usage

thanks a lot for this library!

**Comment by bryanjos** [comment]
I can do that later this evening. I'll also look to see if there are any places in where atoms are required and remove that requirement.

**Comment by bryanjos** [comment]
@werbitzky #43 is a PR with updates that show an example without atoms for keys. I also updated some tests to see if anything would break if strings were used instead of atoms and everything looks to be ok.

**Comment by werbitzky** [comment]
Cool, looks good to me! But maybe I'm overlooking something, as the Guardian creator wrote:

> I agree that it's less than ideal, but without quite a few changes to joken (and maybe even key lists) it's atoms at the moment.

**Comment by bryanjos** [comment]
That may have been true with the older version. The latest one doesn't seem to have that restriction. I'll reply on that issue.

**Comment by bryanjos** [comment]
Going to close this now. Updated the README to show an example without atoms.
