### ISSUE TITLE
LICENSE file

### ISSUE THREAD

**Issue by cs-victor-nascimento** [bryanjos/joken#48]
Right now there is no license in place for this project. I am no expert on this area but just adding a LICENSE file at root and adding a note at README's bottom should suffice.

Do you advocate any specific open source license? If not I guess we should follow Elixir's choice of Apache License 2.0.

I will be glad to do it if that is ok.

**Comment by bryanjos** [comment]
The current one is Apache 2.0. It's defined in the mix.exs file, but it makes sense to have a file for it. I made a PR with the license #50. Should that be ok?

**Comment by bryanjos** [comment]
I Added the license file for Apache 2.0. If there are any issues with it let me know.

**Comment by cs-victor-nascimento** [comment]
It is perfect! Sorry for the delay!
