### ISSUE TITLE
Travis integration

### ISSUE THREAD

**Issue by cs-victor-nascimento** [bryanjos/joken#49]
Since there are more people contributing, it would be good to have some Continuous Integration service building up PRs and the like. Travis is the most famous (IMHO) so I think we should give it a try. Besides this is almost as easy as adding a file (whcich we can base upon plug's for example). After that, we should add the Travis badge to README.

**Comment by bryanjos** [comment]
Sounds good! I'm all for it.

**Comment by bryanjos** [comment]
I turned it on and builds are passing! https://travis-ci.org/bryanjos/joken

I also added the badge to the README.md. Thanks for setting this up!
