### ISSUE TITLE
Allow the config_module key to be placed on any config block

### ISSUE THREAD

**Issue by bryanjos** [bryanjos/joken#54]
Since there is now only one config item for Joken, `config_module`, it would probably be nice to make it so that the user can define which config block contains the key. 

I propose change the `config_module` key to `joken_module`, and adding a using macro that takes an `otp_app` option which defines which config block to look for the `joken_module` key.

Something like below:

```elixir

    #the config block
     config :my_app,
         joken_config: My.Config.Module

  #Next, tell Joken where to find the config block
    use Joken, otp_app: :my_app


  #then to encode and decode
      {:ok, token} = encode_token(%{username: "johndoe"})
      {:ok, decoded_payload} = decode_token(jwt)
```

I made a branch with the change and the only thing I could come up with is having the functions to encode and decode added to the using macro and called directly in the module using it. Since a lot of libraries use `encode` and `decode` as function names, in this branch I renamed the functions `encode_token` and `decode_token`.

**Comment by cs-victor-nascimento** [comment]
This is nice! Some things I think would be useful:

- Perhaps it is good to have the property name as an optional parameter. This way it would be possible to have 2 config modules: one for user login and another for system to system authentication. I don't need this use case but I think it will be desired by people who are coding microservices.
- We could use a `@on_load` to cache the generated JOSE header for each configuration. :smiley:

**Comment by bryanjos** [comment]
Good points. I think making the name of the config property optional makes sense. Or maybe add a property that points directly to the module instead?

I had to look up `@on_load` :smile:. It sounds like that could work.

**Comment by bryanjos** [comment]
@cs-victor-nascimento I added a PR for this, but I haven't added the bit to customize the property itself yet.

Also I'm not sure I completely understand what should be cached using `@on_load`. Could you give me an idea of what to do?

**Comment by cs-victor-nascimento** [comment]
The cache idea is that for each config module the first part of a JWT (which describes de algorithm and optional parameters) will always be the same. Say you choose to use HS256. Then it will always be {"alg": "HS256", "typ": "jwt"} or something. 

So we can generate the JSON and Base64 representation of those once we have that information. Not sure the on_load will work with that (not 100% secure we can ensure our dependencies are all loaded when on_load function is executed) and probably it would be better to go all in and define an application module. I mentioned the on_load just to avoid adding another breaking change: people would need to add joken to their list of apps in mix.exs.

What do you think?

**Comment by cs-victor-nascimento** [comment]
Actually I was thinking and I believe we should have a performance benchmark suite set before atempting any early optimization. I will open another issue for that.

**Comment by bryanjos** [comment]
The caching may work, but I will probably do a separate issue/PR for it. I can probably finish this by adding the ability to customize the config key tonight.

With all the changes going on, the next release will be a big one!

**Comment by bryanjos** [comment]
Closing this as it's no longer valid
