### ISSUE TITLE
Add Plug features

### ISSUE THREAD

**Issue by cs-victor-nascimento** [bryanjos/joken#55]
Many people use plug_jwt or other frameworks that implement JWT signing and verification for Plug. This could be handled directly by Joken. Features that come to mind are:

* A Plug: a plug for verifying if a request has a valid token. This should be configurable per route (using Plugs 0.14.0 ability to assign private options to a connection) with:
  * skipping the route altogether
  * passing specific options to route
  * include some function to operate on the payload
* A Plug function to generate and add the token to a response

An example usage would be:

```elixir
defmodule MyRouter do
  use Plug.Router
  
  @skip_auth %{joken_skip: true}
  @verify_admin %{joken_evaluate: fn(payload) -> payload.role == :admin end}

  plug :match
  plug Joken.Plug, joken_config: MyJWTConfig
  plug :dispatch

  # This will allow requests without an authentication header
  get "/", private: @skip_auth do
    # do stuff
  end

  # this will validate the token and check if the payload has a property role with value :admin
  post "/user", private: @verify_admin do
    # do stuff 
    # generates the token using the config and puts it in response's header
    conn |> Joken.Plug.generate(%{})
    # do stuff
  end

  match _, private: @skip_auth do
    # do stuff
  end
end
```

**Comment by bryanjos** [comment]
I like it! It also covers a use case that is currently an open issue with plug_jwt.

**Comment by cs-victor-nascimento** [comment]
I have a first take on this [here](https://github.com/cs-victor-nascimento/joken/tree/joken_plug).

I did not make a PR yet because I wanted your opinion on something: by default, the JSON we return here has in its field description the reason it failed authorization. This may be okay for development but I think that in production this can be tricky. All information that is public can be used by an attacker. So if he can sign a message properly and he knows that the `:sub` claim is failing then he only needs to attack that claim. Perhaps I am exaggerating...

Thinking about that made me want to let this be customizable. So I did not implement it yet but the plug would also have an optional parameter to configure what the user wants to show in case of error. Actually, I believe the best thing here would be to default returning only 401 with no body (we are assuming all clients will know how to handle JSON) and leave it to be configurable. This would be a breaking change for people migrating from plug_jwt to pure Joken.

Also, I've seen that plug_jwt added a feature of validating claims. I could not follow the reasoning so not sure we must bring it here too.

What do you think?

**Comment by bryanjos** [comment]
Making the error customizable on the plug makes sense. That seems like a good idea.

For the recent update to plug_jwt, what you proposed here for the plug solves the exact problem and in a better way I think.

**Comment by cs-victor-nascimento** [comment]
Okay! So, we have this:
- default behaviour on error will be a blank 401 Unauthorized response
- an option called on_error will map to a function that receives two parameters: conn and message from `{:error, message} = Joken.Token.decode(token)`. If this returns {:body, body_map} we add it to the response. Otherwise we go on with default behaviour.

Is that ok?
