### ISSUE TITLE
Benchmark suite

### ISSUE THREAD

**Issue by cs-victor-nascimento** [bryanjos/joken#59]
Since Joken will probably be a hot path in any APIs in the wild that use it, we need a performance benchmark suite to ensure future changes won't introduce performance regressions.

**Comment by bryanjos** [comment]
Sounds like a good idea. Did you have anything in mind? I've never done a performance benchmark suite of any kind before.

**Comment by cs-victor-nascimento** [comment]
I believe people are going with the [benchfella](https://hex.pm/packages/benchfella) lib. It has a simple configuration and allows us to plug a comparison between runs. It is a lib from one very prolific contributor to Elixir.

I am no expert on benchmarking too and the intention is not really scientific here. But to alarm us on regressions.

I will give it a try.

**Comment by bryanjos** [comment]
Cool! It looks nice, I guess I'm not sure how to set up tests to fail when a performance issue occurs. But I am interested in doing so.
