### ISSUE TITLE
Remove old API from new version

### ISSUE THREAD

**Issue by bryanjos** [bryanjos/joken#65]

**Comment by cs-victor-nascimento** [comment]
Fixed in #67

**Comment by cs-victor-nascimento** [comment]
We are only missing the config module right?

**Comment by bryanjos** [comment]
Yes and the functions in Joken.Token. I'm actually working on removing those now and should have a PR ready soon

**Comment by bryanjos** [comment]
Actually I forgot about updating the benchmarks. I may not have that PR soon :smile:

**Comment by cs-victor-nascimento** [comment]
I guess almost everything went away (and it is now MUCH cleaner)!

The only bits left and that we could discuss if it is worth to add replacements are the ones in Joken.Helpers. I am talking about the validate_** functions.

**Comment by cs-victor-nascimento** [comment]
This one can be closed right? I think we have everything in 0.16.0 now.

Now we should keep updating README (for example with the struct as claims functions) but this is nothing to do with the old API now.
