### ISSUE TITLE
Use string keys by default in new API

### ISSUE THREAD

**Issue by bryanjos** [bryanjos/joken#79]
I asked about what's the best practice for string keys vs atom keys and the response I got was "string keys for user input, atom keys for everything else". I also know that Guardian, which currently uses this library, uses string keys as well. Right now, the default token uses atoms for the claims and validations and the verify function turns the strings into atoms after JSON decoding.

I think we should use strings for keys by default and only use atoms when the user adds a claim or validation using one, a struct is used, and in the case of verify when a struct is given or an option to use atoms is given.

@cs-victor-nascimento what do you think?
@hassox maybe you would like to chime in as well?

**Comment by cs-victor-nascimento** [comment]
That is an interesting question. I believe that with the new API we would never hit a case where the atom was not previously registered. This was a different case back with the old API where we would accept an arbitrary map. Right now you have only `with_claim/2` functions and `with_claims/2` which both accept only known atoms.

I think we are safe here. We are not accepting user input so I believe we are in the "everything else" case here.

**Comment by bryanjos** [comment]
I think the only place we it's an issue is [here](https://github.com/bryanjos/joken/blob/0.16.0/lib/joken/signer.ex#L153) where we turn the string into an atom. If we remove that then I think we are ok.

**Comment by cs-victor-nascimento** [comment]
To remove that we would have to pass a `keys: :atoms!` to decode_payload. I think that would break JSX integration. In any case, that would only pass this line to Poison or JSX. In the end it would still execute it. 

This line is safe as it will only execute AFTER verification is ok. So, in the end, all atoms there should have been registered before. 

I understand the issue here. Perhaps it is better to go binaries all the way to facilitate this behaviour. I think erlang-jose uses only binaries anyway.

**Comment by bryanjos** [comment]
I think using binary keys as a default will be better. I much prefer atoms myself honestly, but I know there are some concerns about using them. I can put together a PR for this today if I get a chance.

**Comment by cs-victor-nascimento** [comment]
I agree with you. It is best to go a safe route here.

On Tue, Sep 1, 2015 at 2:31 PM, Bryan Joseph <notifications@github.com>
wrote:

> I think using binary keys as a default will be better. I much prefer atoms
> myself honestly, but I know there are some concerns about using them. I can
> put together a PR for this today if I get a chance.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bryanjos/joken/issues/79#issuecomment-136805338>.
>



-- 
Victor Oliveira Nascimento
*Concrete* *Solutions*
Senior Analyst/Developer
victor.nascimento@concretesolutions.com.br
http://www.concretesolutions.com.br
Mobile: +55 11 9 8923-8061



Rio de Janeiro                                     São Paulo
Rua São José 90, sala 2121                 Rua Flórida 1670, Sala 22
Cep: 20010-020                                   Cep: 04565-001
Centro - Rio de Janeiro - Brasil             Brooklin - São Paulo – Brasil
Phone : +55 21 2240-2030                   Phone: +55 11 4119 0449

**Comment by bryanjos** [comment]
closed with #80
