### ISSUE TITLE
Create documentation examples on claims

### ISSUE THREAD

**Issue by fire** [bryanjos/joken#93]
It would be helpful if document existed for writing the various claim generators.

Here are some examples, but would like comments.

* nonce (jti claim) 

Probably hmac(random number, (hash(identifier) + now_timestamp)) where the random number is the key and the hashed identifier and timestamp is the data.
* expiration time (exp claim)

with_claim_generator("exp", fn -> current_time + 60 * 1000 end)
* creation time (iat claim)

with_claim_generator("iat", fn -> current_time end)
* nbf claim

with_claim_generator("nbf", fn -> current_time - 100 end)

**Comment by bryanjos** [comment]
We can definitely add more documentation for the claim generators and some examples.

**Comment by cs-victor-nascimento** [comment]
Hey @fire , we have added some more documentation in the wiki. Perhaps, to close this issue, we should mention it in the README.

Does the docs in the wiki help to clarify claim generation?

**Comment by fire** [comment]
I was able to figure it out on my own. Maybe someone else can file bugs if they don't understand.
