### ISSUE TITLE
claim error on compilation

### ISSUE THREAD

**Issue by dfcarpenter** [bryanjos/joken#97]
Keep getting an error when I run mix phoenix.server or phoenix.digest 
Elixir 1.1
Phoenix 1.0.3

```
lib/joken/claims.ex:23: warning: undefined protocol function to_claims/1 (for protocol Joken.Claims)
```

**Comment by bryanjos** [comment]
I was able to reproduce it and looking into it now

**Comment by bryanjos** [comment]
I fixed it and It should be in the next version. For the current version, if you are using a map, struct, or have an explicit implementation of the Joken.Claims protocol for your data type, you should not see any issues.

**Comment by dfcarpenter** [comment]
Wow, thanks for the quick response!
